<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Request\" />
    <None Remove="Services\" />
    <None Remove="Request\Account\" />
    <None Remove="Request\Role\" />
    <None Remove="Request\ChatGroupRequest\" />
    <None Remove="Request\UsersInGroup\" />
    <None Remove="Response\UsersInGroup\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Request\Role\" />
    <Folder Include="Request\ChatGroupRequest\" />
    <Folder Include="Request\UsersInGroup\" />
    <Folder Include="Response\UsersInGroup\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MailKit" Version="4.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.2" />
    <PackageReference Include="MimeKit" Version="4.10.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Twilio" Version="7.8.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
  </ItemGroup>
</Project>
